name: Release

on:
  push:
    tags:
      - 'v*' # For v1.0, v0.1.0, etc

concurrency:
  group: ${{ format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-setup

      - name: Publish with Gradle
        run: ./gradlew -Pver=${{ github.ref_name }} release

      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: Release Build
          path: ${{ github.workspace }}/build/libs/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          files: ${{ github.workspace }}/build/libs/*
          generate_release_notes: true
          name: ${{ format('Release {0}', github.ref_name) }}
          prerelease: ${{ contains(github.ref_name, '-rc-') }}
          fail_on_unmatched_files: true
          draft: true
    outputs:
      url: ${{ steps.release.outputs.url }}
